version: "2"
services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES UTF8; SET CHARACTER SET utf8mb4;'
    ports:
      - "3406:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  web:
    image: enfit/pt:11.1.0
    environment:
      - EMAIL_SERVICE_PORT=1025
      - EMAIL_SERVICE_ADDRESS=mailcatcher
      - LANG=C.UTF-8
    tty: true
    volumes:
      - .:/pt_11_1_0
    ports:
      - "3000:3000"
    depends_on:
      - db
  redis:
    image: redis:6.2.6
    ports:
      - 6679:6379
  sidekiq:
    image: enfit/pt:11.1.0
    # command: bundle exec sidekiq
    environment:
      - EMAIL_SERVICE_PORT=1025
      - EMAIL_SERVICE_ADDRESS=mailcatcher
      - LANG=C.UTF-8
    tty: true
    volumes:
      - .:/pt_11_1_0
    depends_on:
      - db
      - redis
